version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  test:
    jobs:
      - test
